pipeline {
	agent { docker { image 'maven:3.6.3'} }
        stages {
            stage('Build') {
                   steps {
                     echo "mvn --version"
		     echo "Build"
	}
      }
        stage('Build') {
                   steps {
		     
		     echo "Test"
                      
	}
      }
         stage('Build') {
                   steps {
		     
                      echo "Test"
	}
      }
   }
}
